blank_issues_enabled: false

contact_links:

  - name: feature request
    about: To submit a feature request, please use our discussions instead.
    url: https://github.com/spacelandx/space/discussions

  - name: questions
    about: Have any questions? Join our Discord server to get an answer.
    url: https://discord.gg/UQuA3EwXCV
