import type { Snowflake } from "../../types/src/reference.ts";

type RouteParameter = Snowflake | `:${string}`;

// deno-fmt-ignore
export const
  APPLICATION_COMMAND                        = (applicationId: RouteParameter, commandId: RouteParameter) => `/applications/${applicationId}/commands/${commandId}`,
  APPLICATION_COMMANDS                       = (applicationId: RouteParameter) => `/applications/${applicationId}/commands`,
  APPLICATION_ENTITLEMENT                    = (applicationId: RouteParameter, entitlementId: RouteParameter) => `/applications/${applicationId}/entitlements/${entitlementId}`,
  APPLICATION_ENTITLEMENTS                   = (applicationId: RouteParameter) => `/applications/${applicationId}/entitlements`,
  APPLICATION_ENTITLEMENT_CONSUME            = (applicationId: RouteParameter, entitlementId: RouteParameter) => `/applications/${applicationId}/entitlements/${entitlementId}/consume`,
  APPLICATION_GUILD_COMMAND                  = (applicationId: RouteParameter, guildId: RouteParameter, commandId: RouteParameter) => `/applications/${applicationId}/guilds/${guildId}/commands/${commandId}`,
  APPLICATION_GUILD_COMMANDS                 = (applicationId: RouteParameter, guildId: RouteParameter) => `/applications/${applicationId}/guilds/${guildId}/commands`,
  APPLICATION_GUILD_COMMANDS_PERMISSIONS     = (applicationId: RouteParameter, guildId: RouteParameter) => `/applications/${applicationId}/guilds/${guildId}/commands/permissions`,
  APPLICATION_GUILD_COMMAND_PERMISSIONS      = (applicationId: RouteParameter, guildId: RouteParameter, commandId: RouteParameter) => `/applications/${applicationId}/guilds/${guildId}/commands/${commandId}/permissions`,
  APPLICATION_SKUS                           = (applicationId: RouteParameter) => `/applications/${applicationId}/skus`,
  CHANNEL                                    = (channelId: RouteParameter) => `/channels/${channelId}`,
  CHANNEL_FOLLOWERS                          = (channelId: RouteParameter) => `/channels/${channelId}/followers`,
  CHANNEL_INVITES                            = (channelId: RouteParameter) => `/channels/${channelId}/invites`,
  CHANNEL_MESSAGE                            = (channelId: RouteParameter, messageId: RouteParameter) => `/channels/${channelId}/messages/${messageId}`,
  CHANNEL_MESSAGES                           = (channelId: RouteParameter) => `/channels/${channelId}/messages`,
  CHANNEL_MESSAGES_BULK_DELETE               = (channelId: RouteParameter) => `/channels/${channelId}/messages/bulk-delete`,
  CHANNEL_MESSAGE_CROSSPOST                  = (channelId: RouteParameter, messageId: RouteParameter) => `/channels/${channelId}/messages/${messageId}/crosspost`,
  CHANNEL_MESSAGE_REACTION                   = (channelId: RouteParameter, messageId: RouteParameter, emoji: string) => `/channels/${channelId}/messages/${messageId}/reactions/${emoji}`,
  CHANNEL_MESSAGE_REACTIONS                  = (channelId: RouteParameter, messageId: RouteParameter) => `/channels/${channelId}/messages/${messageId}/reactions`,
  CHANNEL_MESSAGE_REACTION_ME                = (channelId: RouteParameter, messageId: RouteParameter, emoji: string) => `/channels/${channelId}/messages/${messageId}/reactions/${emoji}/@me`,
  CHANNEL_MESSAGE_REACTION_USER              = (channelId: RouteParameter, messageId: RouteParameter, emoji: string, userId: RouteParameter) => `/channels/${channelId}/messages/${messageId}/reactions/${emoji}/${userId}`,
  CHANNEL_MESSAGE_THREADS                    = (channelId: RouteParameter, messageId: RouteParameter) => `/channels/${channelId}/messages/${messageId}/threads`,
  CHANNEL_PERMISSION                         = (channelId: RouteParameter, overwriteId: RouteParameter) => `/channels/${channelId}/permissions/${overwriteId}`,
  CHANNEL_PIN                                = (channelId: RouteParameter, messageId: RouteParameter) => `/channels/${channelId}/pins/${messageId}`,
  CHANNEL_PINS                               = (channelId: RouteParameter) => `/channels/${channelId}/pins`,
  CHANNEL_RECIPIENT                          = (channelId: RouteParameter, userId: RouteParameter) => `/channels/${channelId}/recipients/${userId}`,
  CHANNEL_THREADS                            = (channelId: RouteParameter) => `/channels/${channelId}/threads`,
  CHANNEL_THREADS_ACTIVE                     = (channelId: RouteParameter) => `/channels/${channelId}/threads/active`,
  CHANNEL_THREADS_ARCHIVED_PRIVATE           = (channelId: RouteParameter) => `/channels/${channelId}/threads/archived/private`,
  CHANNEL_THREADS_ARCHIVED_PUBLIC            = (channelId: RouteParameter) => `/channels/${channelId}/threads/archived/public`,
  CHANNEL_THREAD_MEMBER                      = (channelId: RouteParameter, userId: RouteParameter) => `/channels/${channelId}/thread-members/${userId}`,
  CHANNEL_THREAD_MEMBERS                     = (channelId: RouteParameter) => `/channels/${channelId}/thread-members`,
  CHANNEL_THREAD_MEMBER_ME                   = (channelId: RouteParameter) => `/channels/${channelId}/thread-members/@me`,
  CHANNEL_TYPING                             = (channelId: RouteParameter) => `/channels/${channelId}/typing`,
  CHANNEL_USER_ME_THREADS_ARCHIVED_PRIVATE   = (channelId: RouteParameter) => `/channels/${channelId}/users/@me/threads/archived/private`,
  CHANNEL_WEBHOOKS                           = (channelId: RouteParameter) => `/channels/${channelId}/webhooks`,
  GATEWAY                                    = "/gateway",
  GATEWAY_BOT                                = "/gateway/bot",
  GUILD                                      = (guildId: RouteParameter) => `/guilds/${guildId}`,
  GUILDS                                     = "/guilds",
  GUILDS_TEMPLATE                            = (templateCode: string) => `/guilds/templates/${templateCode}`,
  GUILD_AUDIT_LOGS                           = (guildId: RouteParameter) => `/guilds/${guildId}/audit-logs`,
  GUILD_BAN                                  = (guildId: RouteParameter, userId: RouteParameter) => `/guilds/${guildId}/bans/${userId}`,
  GUILD_BANS                                 = (guildId: RouteParameter) => `/guilds/${guildId}/bans`,
  GUILD_CHANNELS                             = (guildId: RouteParameter) => `/guilds/${guildId}/channels`,
  GUILD_EMOJI                                = (guildId: RouteParameter, emojiId: RouteParameter) => `/guilds/${guildId}/emojis/${emojiId}`,
  GUILD_EMOJIS                               = (guildId: RouteParameter) => `/guilds/${guildId}/emojis`,
  GUILD_INTEGRATION                          = (guildId: RouteParameter, integrationId: RouteParameter) => `/guilds/${guildId}/integrations/${integrationId}`,
  GUILD_INTEGRATIONS                         = (guildId: RouteParameter) => `/guilds/${guildId}/integrations`,
  GUILD_INVITES                              = (guildId: RouteParameter) => `/guilds/${guildId}/invites`,
  GUILD_MEMBER                               = (guildId: RouteParameter, userId: RouteParameter) => `/guilds/${guildId}/members/${userId}`,
  GUILD_MEMBERS                              = (guildId: RouteParameter) => `/guilds/${guildId}/members`,
  GUILD_MEMBERS_SEARCH                       = (guildId: RouteParameter) => `/guilds/${guildId}/members/search`,
  GUILD_MEMBER_ME_NICK                       = (guildId: RouteParameter) => `/guilds/${guildId}/members/@me/nick`,
  GUILD_MEMBER_ROLE                          = (guildId: RouteParameter, userId: RouteParameter, roleId: RouteParameter) => `/guilds/${guildId}/members/${userId}/roles/${roleId}`,
  GUILD_PREVIEW                              = (guildId: RouteParameter) => `/guilds/${guildId}/preview`,
  GUILD_PRUNE                                = (guildId: RouteParameter) => `/guilds/${guildId}/prune`,
  GUILD_REGIONS                              = (guildId: RouteParameter) => `/guilds/${guildId}/regions`,
  GUILD_ROLE                                 = (guildId: RouteParameter, roleId: RouteParameter) => `/guilds/${guildId}/roles/${roleId}`,
  GUILD_ROLES                                = (guildId: RouteParameter) => `/guilds/${guildId}/roles`,
  GUILD_TEMPLATE                             = (guildId: RouteParameter, templateCode: string) => `/guilds/${guildId}/templates/${templateCode}`,
  GUILD_TEMPLATES                            = (guildId: RouteParameter) => `/guilds/${guildId}/templates`,
  GUILD_VANITY_URL                           = (guildId: RouteParameter) => `/guilds/${guildId}/vanity-url`,
  GUILD_VOICE_STATE                          = (guildId: RouteParameter, userId: RouteParameter) => `/guilds/${guildId}/voice-states/${userId}`,
  GUILD_VOICE_STATE_ME                       = (guildId: RouteParameter) => `/guilds/${guildId}/voice-states/@me`,
  GUILD_WEBHOOKS                             = (guildId: RouteParameter) => `/guilds/${guildId}/webhooks`,
  GUILD_WELCOME_SCREEN                       = (guildId: RouteParameter) => `/guilds/${guildId}/welcome-screen`,
  GUILD_WIDGET                               = (guildId: RouteParameter) => `/guilds/${guildId}/widget`,
  GUILD_WIDGET_JSON                          = (guildId: RouteParameter) => `/guilds/${guildId}/widget.json`,
  GUILD_WIDGET_PNG                           = (guildId: RouteParameter) => `/guilds/${guildId}/widget.png`,
  INTERACTION_TOKEN_CALLBACK                 = (interactionId: RouteParameter, interactionToken: string) => `/interactions/${interactionId}/${interactionToken}/callback`,
  INVITE                                     = (inviteCode: string) => `/invites/${inviteCode}`,
  OAUTH2_APPLICATION_ME                      = "/oauth2/applications/@me",
  OAUTH2_ME                                  = "/oauth2/@me",
  STAGE_INSTANCE                             = (channelId: RouteParameter) => `/stage-instances/${channelId}`,
  STAGE_INSTANCES                            = "/stage-instances",
  STORE_SKU_DISCOUNT                         = (skuId: RouteParameter, userId: RouteParameter) => `/store/skus/${skuId}/discounts/${userId}`,
  USER                                       = (userId: RouteParameter) => `/users/${userId}`,
  USER_ME                                    = "/users/@me",
  USER_ME_CHANNELS                           = "/users/@me/channels",
  USER_ME_CONNECTIONS                        = "/users/@me/connections",
  USER_ME_GUILD                              = (guildId: RouteParameter) => `/users/@me/guilds/${guildId}`,
  USER_ME_GUILDS                             = "/users/@me/guilds",
  VOICE_REGIONS                              = "/voice/regions",
  WEBHOOK                                    = (webhookId: RouteParameter) => `/webhooks/${webhookId}`,
  WEBHOOK_INTERACTION_TOKEN                  = (applicationId: RouteParameter, interactionToken: string) => `/webhooks/${applicationId}/${interactionToken}`,
  WEBHOOK_INTERACTION_TOKEN_MESSAGE          = (applicationId: RouteParameter, interactionToken: string, messageId: RouteParameter) => `/webhooks/${applicationId}/${interactionToken}/messages/${messageId}`,
  WEBHOOK_INTERACTION_TOKEN_MESSAGE_ORIGINAL = (applicationId: RouteParameter, interactionToken: string) => `/webhooks/${applicationId}/${interactionToken}/messages/@original`,
  WEBHOOK_TOKEN                              = (webhookId: RouteParameter, webhookToken: string) => `/webhooks/${webhookId}/${webhookToken}`,
  WEBHOOK_TOKEN_GITHUB                       = (webhookId: RouteParameter, webhookToken: string) => `/webhooks/${webhookId}/${webhookToken}/github`,
  WEBHOOK_TOKEN_MESSAGE                      = (webhookId: RouteParameter, webhookToken: string, messageId: RouteParameter) => `/webhooks/${webhookId}/${webhookToken}/messages/${messageId}`,
  WEBHOOK_TOKEN_SLACK                        = (webhookId: RouteParameter, webhookToken: string) => `/webhooks/${webhookId}/${webhookToken}/slack`;
