# https://github.com/denoland/setup-deno

name: ci

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno:
          - v1.x
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
      - run: deno lint
      - run: deno fmt --check
      - run: deno test -A --unstable
