# https://github.com/denoland/setup-deno

name: ci

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno:
          - v1.x
          - nightly
        os:
          - macOS-latest
          - windows-latest
          - ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main

      - name: Cache Dependencies
        run: deno cache lib/client/deps.ts

      - name: Lint Code
        run: deno lint --unstable

      - name: Format Code
        run: deno fmt

      # - name: Run Tests
      #   run: deno test -A --unstable
